Feat/create debate room
1F10230048/resbattle-arena pull request #14
Opened 2024-08-22 08:01 UTC by 1F10230048

## issue

resolve #13 

## description
debate_roomsテーブル　roomCreateAPI　テスト用ページ(/room/create)を仮で作成しました

2024-08-22 08:23 UTC, skmtrd submitted a review, later dismissed
見ました〜！
動作確認(ちゃんとdbに保存されるか)ができているなら良きかと！

2024-08-22 08:36 UTC, skmtrd commented on src/app/room/create/page.tsx
> +        />
playerId はdbに保存されている既に存在しているものを使う方が良いと思うので
新しくユーザーに入力して貰う必要はなさそう？

2024-08-22 08:36 UTC, skmtrd commented on src/app/room/create/page.tsx
> +  const [roomStatus, setroomStatus] = useState<string>('undefined')
ここはあくまでもroom/create なので作成中のルームのステータスを保つ必要はあまりないかも

2024-08-22 08:36 UTC, skmtrd commented on src/app/room/create/page.tsx
> +  const [roomId, setroomId] = useState<string>('undefined')
ここもステータス同様、作成ページではステートで持たなくてもよい

2024-08-22 14:49 UTC, mst-mkt requested changes

2024-08-22 14:49 UTC, mst-mkt commented on src/app/api/[[...route]]/route.ts
> +const route = app.route('/health', healthRoute).route('/room/create', createRoomRoute)
`/room/create`じゃなくてここでは`/room`で切ってroomのほうでcreateにきったほうがわかりやすいかも？
(今後`/room/hoge`が増えるだろうので)

2024-08-22 14:49 UTC, mst-mkt commented on src/drizzle/schema.ts
> +  id: text('id')
`uuid`のカラムできたような？

2024-08-22 16:16 UTC, 1F10230048 commented
idをuuid型に変更するときにmigrationがエラーになったのでmigrationファイルをリセットしました。

2024-08-23 06:45 UTC, 1F10230048 commented
ゲーム開始までを作っていきます。

2024-08-23 14:46 UTC, mst-mkt requested changes

2024-08-23 14:46 UTC, mst-mkt commented on src/app/api/[[...route]]/room/create/index.ts
> +    return c.json({ room_id: newRoom[0].id, status: newRoom[0].status }, 201)
こうするとき、`[0]`ってアクセスするのあれなときは下みたいにやってみてもいいかも

```ts
const [newRoom] = await dbClient
  .insert(debateRooms)
  .values({
    topic,
    player1_id,
  })
  .returning()

return c.json({ room_id: newRoom.id, status: newRoom.status }, 201)
```

2024-08-23 14:46 UTC, mst-mkt commented on src/app/room/create/page.tsx
> +  const [topic, setTopic] = useState<string>('')
この場合の`<string>`は不要かも

2024-08-23 14:46 UTC, mst-mkt commented on src/app/room/[roomId]/page.tsx
> +            <Link href={'/'}>ホームに戻る</Link>
href="/"でいいかも

2024-08-23 15:56 UTC, mst-mkt approved these changes

2024-08-23 15:56 UTC, merged