Fix/deploy error
1F10230048/resbattle-arena pull request #8
Opened 2024-08-21 18:41 UTC by 1F10230048

## issue

resolve #6 #7 

## description
デプロイとzodエラーの修正

2024-08-22 14:39 UTC, mst-mkt requested changes

2024-08-22 14:39 UTC, mst-mkt commented on src/app/ApiStatus.tsx
> +    const fetachAndSet = async () => {
`fetachAndSet`->`fetchAndSet`

2024-08-22 14:39 UTC, mst-mkt commented on src/app/ApiStatus.tsx
> +    fetachAndSet()
apiが死んでてerrorになったときにずっとloadingなのはよくなさそう

```ts
try {
   // fetch    // ここでres.ok見てthrowしてもいいかも
   // set
} catch (e) {
  // set "error"
}
```

とかにしても良さそう

2024-08-23 06:57 UTC, 1F10230048 commented
ホームを編集したいためクローズとさせてください。

2024-08-23 06:57 UTC, closed without merging